USE tempdb;
DBCC SHRINKFILE('templog3', EMPTYFILE);

USE master;
ALTER DATABASE tempdb REMOVE FILE temp9;


USE tempdb;
SELECT name, size*8/1024 AS SizeMB
FROM sys.database_files;

ALTER DATABASE tempdb MODIFY FILE (NAME = 'tempdev', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp2', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp3', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp4', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp5', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp6', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp7', SIZE = 2048MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp8', SIZE = 2048MB);

-- Repita para os demais arquivos (exceto o temp9, que será removido)

ALTER DATABASE tempdb MODIFY FILE (NAME = 'tempdev', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp2', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp3', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp4', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp5', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp6', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp7', FILEGROWTH = 512MB);
ALTER DATABASE tempdb MODIFY FILE (NAME = 'temp8', FILEGROWTH = 512MB);

-- Repita para os demais arquivos

